# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-05 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('commit', models.TextField(blank=True, null=True)),
                ('com_time', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lipstick',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('goods_name', models.TextField(blank=True, null=True)),
                ('goods_price', models.TextField(blank=True, null=True)),
                ('goods_img', models.TextField(blank=True, null=True)),
                ('sales', models.TextField(blank=True, null=True)),
                ('shops', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lipstick',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('goods_name', models.TextField(blank=True, null=True)),
                ('goods_price', models.TextField(blank=True, null=True)),
                ('goods_img', models.TextField(blank=True, null=True)),
                ('sales', models.TextField(blank=True, null=True)),
                ('shops', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mask',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('reserver', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
