# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-09 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_perfume'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBCream',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('goods_name', models.TextField(blank=True, null=True)),
                ('goods_price', models.TextField(blank=True, null=True)),
                ('goods_img', models.TextField(blank=True, null=True)),
                ('sales', models.TextField(blank=True, null=True)),
                ('shops', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BBCream',
                'managed': False,
            },
        ),
    ]
